### PR TITLE
Remove flake8 and use black instead

### PR DESCRIPTION
**Pull request by Amund211**
This PR suffers from scope-creep, but basically:
- Use black to check code formatting, removing the need to keep flake8 around
- Also check code formatting in `nablaweb/` and `manage.py`
- Add `make diff` to view the proposed changes to code formatting

It seemed a bit weird to have flake8 verifying the formatting when it is black that is actually doing it. Was there a reason for this?

### CODE REVIEW

**Comment by Amund211** [comment]
Outdated

**Comment by Northo** [comment]
Wow, I have been slow on GitHub this summer! I believe that there was some formatting where `black` did not catch the mistake, but `flake8` did. But I don't remember, to be honest. Luckily I didn't document anything...

**Comment by Amund211** [comment]
I've come to realize the same thing. I'm working on a better setup with github actions.

**Comment by Northo** [comment]
Nice

**Pull request closed without merging**
